global:
    scrape_interval: 5s
    evaluation_interval: 5s

rule_files:
    - rules.yml

scrape_configs:
    - job_name: model_mock
      static_configs:
          - targets:
                - localhost:5000

alerting:
    alertmanagers:
        - static_configs:
              - targets:
                   - localhost:9093
